### ISSUE TITLE
Issues from Milestone 2

### ISSUE THREAD

**Issue by gunishakaur** [UBC-MDS/vancouver-tree-height-geo-group-33#46]
- [ ] No software or packages versions are not pinned in the environment specification file(s). None of the package versions are pinned down in any kind of format like yaml file or Dockerfile
- [ ] Tag is missing to specify which version of the image to use
- [ ] Could not reproducibly run the analysis because one package was missing from the provided computational environment.
- [ ] Had to change something in the computational environment files to run the analysis
- [ ] Latest tag was used for docker. This is not ideal because if the user has latest locally, but there is a newer version on the container registry, then Docker will not pull it.
- [ ] Your instructions points to building the "latest" version of the image, this happens when you dont specify its tag and take the default which is latest. Then, when opened the docker container, it requires installation of several latex packages, which should be completed before hand as well

**Comment by derekrodgers** [comment]
Resolved `Tag is missing to specify which version of the image to use` in #54

**Comment by derekrodgers** [comment]
This solves all other issues below that as well!
