### ISSUE TITLE
Issues from Milestone 1

### ISSUE THREAD

**Issue by gunishakaur** [UBC-MDS/vancouver-tree-height-geo-group-33#48]
Gradescope issues needs to be addressed from Milestone 1

- [x] Abstract/Summary- Does not clearly report the major findings.
- [x] Methods- The data should be reproducibly downloaded from it's source using code in the analysis code document, and a copy saved in the data directory (and ideally in the data/raw subdirectory).
- [x] Reproducibility- Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing, some guessing and/or trial and error had to be performed to run the project).
- [x] Organisation and structure- The analysis notebook (.ipynb or .Qmd or *Rmd) should be in a sub-directory called something sensible, such as analysis, src, notebooks, docs, etc, to aid in the discoverability of this file, and related ones. Having too many files in the project root makes the project organization less understandable and can lead to longer activation times to productivity for collaborators (including future you!).
- [x] Readme- Summary in README should include high-level interpretation of analysis findings, as well 1-2 sentences on what they might mean (at least at a high-level).
- [x] README should include include instructions on how to run the analysis.

**Comment by gunishakaur** [comment]
- [X] Abstract/Summary- Does not clearly report the major findings.
- [X] Methods- The data should be reproducibly downloaded from it's source using code in the analysis code document, and a copy saved in the data directory (and ideally in the data/raw subdirectory).
- [ ] Reproducibility- Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing, some guessing and/or trial and error had to be performed to run the project).
- [X] Organisation and structure- The analysis notebook (.ipynb or .Qmd or *Rmd) should be in a sub-directory called something sensible, such as analysis, src, notebooks, docs, etc, to aid in the discoverability of this file, and related ones. Having too many files in the project root makes the project organization less understandable and can lead to longer activation times to productivity for collaborators (including future you!).
- [ ] Readme- Summary in README should include high-level interpretation of analysis findings, as well 1-2 sentences on what they might mean (at least at a high-level).
- [X] README should include include instructions on how to run the analysis.
